/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jbunting' at '3/6/15 2:56 PM' with Gradle 2.3
 *
 * @author jbunting, @date 3/6/15 2:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
